"""add email to users

Revision ID: 8fea6281a8fc
Revises: 3a6db02afba9
Create Date: 2025-12-21 17:42:02.210390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel #ADD THIS HERE


# revision identifiers, used by Alembic.
revision: str = '8fea6281a8fc'
down_revision: Union[str, Sequence[str], None] = '3a6db02afba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_unique_constraint('email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
