"""added password

Revision ID: aad83b7d0c72
Revises: 8fea6281a8fc
Create Date: 2025-12-24 16:12:00.205335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel #ADD THIS HERE


# revision identifiers, used by Alembic.
revision: str = 'aad83b7d0c72'
down_revision: Union[str, Sequence[str], None] = '8fea6281a8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
